criterion:
  name: ce

optimizer:
  name: prodigy
  lr: 1
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00002

run:
  experiment: "cifar10_resnet18_train"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

noise:
  phase_bias: 0
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0.05
  output_noise_std: 0
  random_state: 42
  weight_noise_std: 0.0
  crosstalk_flag: 0
  noise_flag: 0
  crosstalk_scheduler:
    interv_h: 20
    interv_v: 120
    interv_s: 9

quantize:
  weight_bit: 8
  input_bit: 8

noise:
  phase_noise_std: 0
  crosstalk_factor: 0.05
  random_state: 42

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/resnet18/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""

model:
  name: "TeMPO_ResNet18"

debug:
  verboise: 1

dst_scheduler:
  death_rate: 0.5
  growth_death_ratio: 1.0
  death_rate_decay: cosine
  death_mode: magnitude
  growth_mode: gradient
  redistribution_mode: null
  spe_initial: null
  pruning_type: unstructure
  update_frequency: 1400
  T_max: 0.8
  density: 0.8
  init_mode: uniform