criterion:
  name: ce

optimizer:
  name: prodigy
  lr: 1
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00002

run:
  experiment: "cifar10_vgg8_train"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

quantize:
  weight_bit: 8
  input_bit: 8

noise:
  phase_noise_std: 0
  crosstalk_factor: 0.05
  random_state: 42

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/vgg8/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""

model:
  name: "TeMPO_VGG8"

debug:
  verboise: 1

