criterion:
  name: ce

optimizer:
  name: prodigy
  lr: 1
  weight_decay: 0.01

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00002

run:
  experiment: "fmnist_cnn_train"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

quantize:
  weight_bit: 8
  input_bit: 8

noise:
  phase_noise_std: 0
  crosstalk_factor: 0.05
  random_state: 42
  crosstalk_scheduler:
    interv_h: 15
    interv_v: 120
    interv_s: 10
  noise_flag: 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "fmnist/cnn/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""

model:
  name: "TeMPO_CNN"
  conv_cfg:
    miniblock: [2, 2, 4, 4]
  linear_cfg:
    miniblock: [2, 2, 4, 4]
  kernel_list: [16, 16, 16]
  kernel_size_list: [1, 1, 1]
  hidden_list: []
  stride_list: [1, 1, 1]
  padding_list: [1, 1, 1]
  pool_out_size: 5

debug:
  verboise: 1

dst_scheduler:
  death_rate: 0.5
  growth_death_ratio: 1.0
  death_rate_decay: cosine
  death_mode: magnitude_power_crosstalk
  growth_mode: gradient_power_crosstalk
  redistribution_mode: null
  spe_initial: null
  pruning_type: structure_col
  update_frequency: 1400
  T_max: 0.8
  density: 0.5
  max_combinations: 100
  init_mode: uniform_power_crosstalk
  power_choice_margin: 2
  node_spacing: [20, 100] # um, row, col spacing in weight matrix